/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 349bdbc857b7daa338fbb71d64124ea9)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	R2_ACCOUNT_ID: string;
	R2_BUCKET_NAME: string;
	CORS_ORIGINS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.output/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_ANON_KEY" | "R2_ACCOUNT_ID" | "R2_BUCKET_NAME" | "CORS_ORIGINS">> {}
}
